### ISSUE TITLE
Anomaly Maps and Anomaly Scores

### ISSUE THREAD

**Issue by rishabh-akridata** [TArdelean/BlindLCA#1]
Hello @TArdelean,
I am trying to run this code as per the steps mentioned in the README on the carpet class of MVtec dataset. The anomaly maps looks good for the defective classes, however for the good class also the anomaly maps shows very strong highlighting. And how we can get the image level anomaly scores. Is it just the max(anomaly_maps)?
![Screenshot 2024-10-23 at 2 59 36 PM](https://github.com/user-attachments/assets/f479722b-7838-4a3d-88f0-baa4690d700e)

[Good class]
![Screenshot 2024-10-23 at 2 59 55 PM](https://github.com/user-attachments/assets/44e2dd20-54a0-4033-82e3-c74206eed226)

[Defective class(hole)]
![Screenshot 2024-10-23 at 3 00 05 PM](https://github.com/user-attachments/assets/f0d21fd4-da8b-4dc4-ae4c-f0c27fe04334)

Thanks.

**Comment by TArdelean** [comment]
Hi @rishabh-akridata,

Firstly, thanks for your interest in our work. 
The reason the anomaly maps you show have large activations even for **good** image is because the maps are normalized for visualization; therefore all maps will have at least one pixel with maximum brightness. One way to get around this is to normalize the scores at level of the dataset instead of normalizing at the level of each image.
And to your second question: yes, the image-level anomaly score is usually computed as the maximum value in the anomaly map.

Best,
Timotei

**Comment by rishabh-akridata** [comment]
Hi @TArdelean,
Is it possible to give the evaluation code for AUROCi and AUROCp calculation as well as mentioned in the paper for the MVTec Textures Dataset? Because the current code only gives the NMI and clustering related metrics.
![Screenshot 2024-10-24 at 3 38 04 PM](https://github.com/user-attachments/assets/fb5f6c8b-5622-4e62-a611-8a65e731d540)

Thanks

**Comment by TArdelean** [comment]
Hi, 
For the anomaly maps metrics, please refer to the evaluation code from the authors of the MVTecAD dataset: https://www.mvtec.com/company/research/datasets/mvtec-ad. This integration of the evaluation code might also prove useful: https://github.com/TArdelean/AnomalyLocalizationFCA.

Best regards,
Timotei

**Comment by rishabh-akridata** [comment]
Thanks.

**Comment by TArdelean** [comment]
You are welcome!
