### ISSUE TITLE
Using FCA on batch of Residuals.

### ISSUE THREAD

**Issue by rishabh-akridata** [TArdelean/BlindLCA#2]
Hello @TArdelean,
The current code works fine for residuals of shape (1, 512, 64, 64). How can we apply fca on batch of residuals of shape (batch, 512, 64, 64)? What changes and where I need to do inorder to use it in batches?

Thanks.

**Comment by TArdelean** [comment]
Hi @rishabh-akridata,

The current implementation of FCA only supports a batch size of one. Because of the high memory consumption at large resolution, one can usually process only one image at a time anyway. To process a larger batch you can use a for loop, or try vmap (https://pytorch.org/docs/stable/generated/torch.vmap.html) to apply FCA in a vectorized fashion.
